### ISSUE TITLE
have you tried this with yarn?

### ISSUE THREAD

**Issue by unitedworx** [erikgall/envoyer-npm-deployment#4]
Have you tried this with yarn? to see what different it makes it terms of speed? yarn caches locally all the repos so after the first install it should be considerably faster than npm install! also it stores a .lock file like composer so its a safer bet to have each same dependency versions across environments.  

I like you idea of sym linking the node_modules into the project folder like its done with the storage folder, makes sense to do so! I a now wondering why we don't do the same for composer dependancies so speed up deployments! 

My initial idea was to move node_modules from current to new release before activating the new release but you solution is better!

**Comment by erikgall** [comment]
I have tried it with Yarn and it works even faster.. The only reason that I didn't use Yarn when I created this was due to a problem with Laravel Mix and Yarn at the time. 

I never thought about using it with Composer but it might be worth a try.. I could be wrong but I'm pretty sure Composer caches repos locally, as well.

🍻  Cheers!

**Comment by unitedworx** [comment]
Thanks for the reply ,will give it a go and see how things work. I have been holding back on compiling assets on the server for several reasons especially time to complete the deployments but things are looking good.
